#! /bin/sh
### BEGIN INIT INFO
# Provides:          musicshare
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

VIRTUAL_ENV=/home/pi/.virtualenvs/fsObs
PYTHON_BIN=$VIRTUAL_ENV/bin/python
PROJECT_HOME=/home/pi/projects/auto_updater
DAEMON=$PROJECT_HOME/auto_updater/__main__.py
DAEMON_NAME=autoupdater

DAEMON_USER=pi

PIDFILE=/home/pi/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

start() {
        log_daemon_msg "Starting system $DAEMON_NAME daemon"
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --chuid $DAEMON_USER --startas $DAEMON
        log_end_msg $?
}

stop () {
        log_daemon_msg "Stopping system $DAEMON_NAME daemon"
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        log_end_msg $?
}

case "$1" in
        start)
                start
                ;;
        stop)
		stop
                ;;
        *)
                echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
